import AsyncStorage from "@react-native-async-storage/async-storage";
import { ConvexReactClient } from "convex/react";
import type { FunctionReference } from "convex/server";

const MIGRATION_KEY = "@statcheck_migration_complete";

export type MigrationStatus =
  | "pending"
  | "in_progress"
  | "complete"
  | "error";

/**
 * Check if migration has already been completed
 */
export async function isMigrationComplete(): Promise<boolean> {
  const status = await AsyncStorage.getItem(MIGRATION_KEY);
  return status === "true";
}

/**
 * Mark migration as complete
 */
async function markMigrationComplete(): Promise<void> {
  await AsyncStorage.setItem(MIGRATION_KEY, "true");
}

/**
 * Migrate all AsyncStorage data to Convex
 */
export async function migrateAsyncStorageToConvex(
  convexClient: ConvexReactClient,
  userId: string,
  api: any // Type will be generated by Convex
): Promise<void> {
  // Check if already migrated
  const alreadyMigrated = await isMigrationComplete();
  if (alreadyMigrated) {
    console.log("[Migration] Already completed, skipping");
    return;
  }

  console.log("[Migration] Starting data migration to Convex...");

  try {
    // 1. Migrate Lists
    console.log("[Migration] Migrating lists...");
    const listsData = await AsyncStorage.getItem("lists");
    if (listsData) {
      const lists = JSON.parse(listsData);
      console.log(`[Migration] Found ${lists.length} lists to migrate`);

      for (const list of lists) {
        try {
          // Create the list
          const listId = await convexClient.mutation(api.userLists.createList, {
            userId,
            name: list.name,
            description: list.description,
          });

          // Add players to the list
          if (list.players && list.players.length > 0) {
            for (const player of list.players) {
              await convexClient.mutation(api.userLists.addPlayerToList, {
                listId,
                playerId: player.playerId,
              });
            }

            // Reorder to match original order
            await convexClient.mutation(api.userLists.reorderPlayersInList, {
              listId,
              newOrder: list.players,
            });
          }

          // Add links to the list
          if (list.links && list.links.length > 0) {
            for (const link of list.links) {
              await convexClient.mutation(api.userLists.addLinkToList, {
                listId,
                url: link.url,
                title: link.title,
              });
            }
          }

          console.log(`[Migration] ✓ Migrated list: ${list.name}`);
        } catch (error) {
          console.error(`[Migration] ✗ Failed to migrate list: ${list.name}`, error);
        }
      }
    }

    // 2. Migrate Player Links
    console.log("[Migration] Migrating player links...");
    const linksData = await AsyncStorage.getItem("player_links");
    if (linksData) {
      const linksMap = JSON.parse(linksData);
      const playerIds = Object.keys(linksMap);
      console.log(`[Migration] Found links for ${playerIds.length} players`);

      for (const playerId of playerIds) {
        const links = linksMap[playerId];
        if (Array.isArray(links)) {
          for (const link of links) {
            try {
              await convexClient.mutation(api.playerLinks.addPlayerLink, {
                userId,
                playerId,
                url: link.url,
                title: link.title,
              });
            } catch (error) {
              console.error(`[Migration] ✗ Failed to migrate link for player ${playerId}`, error);
            }
          }
          console.log(`[Migration] ✓ Migrated ${links.length} links for player ${playerId}`);
        }
      }
    }

    // 3. Migrate Recent Players
    console.log("[Migration] Migrating recent players...");
    const recentData = await AsyncStorage.getItem("@statcheck_recent_players");
    if (recentData) {
      const recentPlayers = JSON.parse(recentData);
      console.log(`[Migration] Found ${recentPlayers.length} recent players`);

      for (const player of recentPlayers) {
        try {
          await convexClient.mutation(api.recentPlayers.addRecentPlayer, {
            userId,
            player,
          });
        } catch (error) {
          console.error(`[Migration] ✗ Failed to migrate recent player: ${player.name}`, error);
        }
      }
      console.log(`[Migration] ✓ Migrated ${recentPlayers.length} recent players`);
    }

    // 4. Migrate Theme Settings
    console.log("[Migration] Migrating theme settings...");
    const themeData = await AsyncStorage.getItem("@statcheck_theme");
    if (themeData) {
      const theme = JSON.parse(themeData) as "light" | "dark";
      try {
        await convexClient.mutation(api.userSettings.updateUserSettings, {
          userId,
          theme,
        });
        console.log(`[Migration] ✓ Migrated theme: ${theme}`);
      } catch (error) {
        console.error("[Migration] ✗ Failed to migrate theme", error);
      }
    }

    // Mark migration as complete
    await markMigrationComplete();
    console.log("[Migration] ✅ Migration completed successfully!");

    // Optional: Keep AsyncStorage data for backup (don't delete)
    // Users can manually clear it later if needed
  } catch (error) {
    console.error("[Migration] ❌ Migration failed:", error);
    throw error;
  }
}

/**
 * Clear the migration flag (for testing or reset)
 */
export async function resetMigration(): Promise<void> {
  await AsyncStorage.removeItem(MIGRATION_KEY);
  console.log("[Migration] Reset migration flag");
}
