import { mutation } from "./_generated/server";

interface DraftPick {
  year: number;
  round: number;
  originalTeam: string;
  conditions?: string;
  swapRights?: boolean;
  viaTradeWith?: string;
}

interface TeamDraftPicks {
  teamId: number;
  teamAbbreviation: string;
  picks: DraftPick[];
}

// NBA Draft Picks data for all 30 teams
// Data manually compiled from RealGM/ESPN
// Update this when trades happen or after the draft
const NBA_DRAFT_PICKS: TeamDraftPicks[] = [
  {
    teamId: 1,
    teamAbbreviation: "ATL",
    picks: [
      { year: 2025, round: 1, originalTeam: "ATL" },
      { year: 2025, round: 2, originalTeam: "ATL" },
      { year: 2026, round: 1, originalTeam: "ATL" },
      { year: 2026, round: 2, originalTeam: "ATL" },
      { year: 2027, round: 1, originalTeam: "ATL" },
      { year: 2027, round: 2, originalTeam: "ATL" },
      { year: 2028, round: 1, originalTeam: "ATL" },
      { year: 2028, round: 2, originalTeam: "ATL" },
      { year: 2029, round: 1, originalTeam: "ATL" },
      { year: 2029, round: 2, originalTeam: "ATL" },
      { year: 2030, round: 1, originalTeam: "ATL" },
      { year: 2030, round: 2, originalTeam: "ATL" },
      { year: 2031, round: 1, originalTeam: "ATL" },
      { year: 2031, round: 2, originalTeam: "ATL" },
    ],
  },
  {
    teamId: 2,
    teamAbbreviation: "BOS",
    picks: [
      { year: 2025, round: 1, originalTeam: "BOS" },
      { year: 2025, round: 2, originalTeam: "BOS" },
      { year: 2026, round: 1, originalTeam: "BOS" },
      { year: 2026, round: 2, originalTeam: "BOS" },
      { year: 2027, round: 1, originalTeam: "BOS" },
      { year: 2027, round: 2, originalTeam: "BOS" },
      { year: 2028, round: 1, originalTeam: "BOS" },
      { year: 2028, round: 2, originalTeam: "BOS" },
      { year: 2029, round: 1, originalTeam: "BOS" },
      { year: 2029, round: 2, originalTeam: "BOS" },
      { year: 2030, round: 1, originalTeam: "BOS" },
      { year: 2030, round: 2, originalTeam: "BOS" },
      { year: 2031, round: 1, originalTeam: "BOS" },
      { year: 2031, round: 2, originalTeam: "BOS" },
    ],
  },
  {
    teamId: 3,
    teamAbbreviation: "BKN",
    picks: [
      { year: 2025, round: 1, originalTeam: "PHX", conditions: "Top 3 protected", viaTradeWith: "PHX" },
      { year: 2025, round: 2, originalTeam: "BKN" },
      { year: 2026, round: 1, originalTeam: "BKN" },
      { year: 2026, round: 1, originalTeam: "DAL", conditions: "Top 4 protected", viaTradeWith: "DAL" },
      { year: 2026, round: 2, originalTeam: "BKN" },
      { year: 2027, round: 1, originalTeam: "BKN" },
      { year: 2027, round: 1, originalTeam: "PHX", swapRights: true },
      { year: 2027, round: 2, originalTeam: "BKN" },
      { year: 2028, round: 1, originalTeam: "BKN" },
      { year: 2028, round: 2, originalTeam: "BKN" },
      { year: 2029, round: 1, originalTeam: "BKN" },
      { year: 2029, round: 1, originalTeam: "PHX", conditions: "Unprotected", viaTradeWith: "PHX" },
      { year: 2029, round: 2, originalTeam: "BKN" },
      { year: 2030, round: 1, originalTeam: "BKN" },
      { year: 2030, round: 2, originalTeam: "BKN" },
      { year: 2031, round: 1, originalTeam: "BKN" },
      { year: 2031, round: 2, originalTeam: "BKN" },
    ],
  },
  {
    teamId: 4,
    teamAbbreviation: "CHA",
    picks: [
      { year: 2025, round: 1, originalTeam: "CHA" },
      { year: 2025, round: 2, originalTeam: "CHA" },
      { year: 2026, round: 1, originalTeam: "CHA" },
      { year: 2026, round: 2, originalTeam: "CHA" },
      { year: 2027, round: 1, originalTeam: "CHA" },
      { year: 2027, round: 2, originalTeam: "CHA" },
      { year: 2028, round: 1, originalTeam: "CHA" },
      { year: 2028, round: 2, originalTeam: "CHA" },
      { year: 2029, round: 1, originalTeam: "CHA" },
      { year: 2029, round: 2, originalTeam: "CHA" },
      { year: 2030, round: 1, originalTeam: "CHA" },
      { year: 2030, round: 2, originalTeam: "CHA" },
      { year: 2031, round: 1, originalTeam: "CHA" },
      { year: 2031, round: 2, originalTeam: "CHA" },
    ],
  },
  {
    teamId: 5,
    teamAbbreviation: "CHI",
    picks: [
      { year: 2025, round: 1, originalTeam: "CHI" },
      { year: 2025, round: 2, originalTeam: "CHI" },
      { year: 2026, round: 1, originalTeam: "CHI" },
      { year: 2026, round: 2, originalTeam: "CHI" },
      { year: 2027, round: 1, originalTeam: "CHI" },
      { year: 2027, round: 2, originalTeam: "CHI" },
      { year: 2028, round: 1, originalTeam: "CHI" },
      { year: 2028, round: 2, originalTeam: "CHI" },
      { year: 2029, round: 1, originalTeam: "CHI" },
      { year: 2029, round: 2, originalTeam: "CHI" },
      { year: 2030, round: 1, originalTeam: "CHI" },
      { year: 2030, round: 2, originalTeam: "CHI" },
      { year: 2031, round: 1, originalTeam: "CHI" },
      { year: 2031, round: 2, originalTeam: "CHI" },
    ],
  },
  {
    teamId: 6,
    teamAbbreviation: "CLE",
    picks: [
      { year: 2025, round: 1, originalTeam: "CLE" },
      { year: 2025, round: 2, originalTeam: "CLE" },
      { year: 2026, round: 1, originalTeam: "CLE" },
      { year: 2026, round: 2, originalTeam: "CLE" },
      { year: 2027, round: 1, originalTeam: "CLE" },
      { year: 2027, round: 2, originalTeam: "CLE" },
      { year: 2028, round: 1, originalTeam: "CLE" },
      { year: 2028, round: 2, originalTeam: "CLE" },
      { year: 2029, round: 1, originalTeam: "CLE" },
      { year: 2029, round: 2, originalTeam: "CLE" },
      { year: 2030, round: 1, originalTeam: "CLE" },
      { year: 2030, round: 2, originalTeam: "CLE" },
      { year: 2031, round: 1, originalTeam: "CLE" },
      { year: 2031, round: 2, originalTeam: "CLE" },
    ],
  },
  {
    teamId: 7,
    teamAbbreviation: "DAL",
    picks: [
      { year: 2025, round: 1, originalTeam: "DAL" },
      { year: 2025, round: 2, originalTeam: "DAL" },
      { year: 2027, round: 1, originalTeam: "DAL" },
      { year: 2027, round: 2, originalTeam: "DAL" },
      { year: 2028, round: 1, originalTeam: "DAL" },
      { year: 2028, round: 2, originalTeam: "DAL" },
      { year: 2029, round: 1, originalTeam: "DAL" },
      { year: 2029, round: 2, originalTeam: "DAL" },
      { year: 2030, round: 1, originalTeam: "DAL" },
      { year: 2030, round: 2, originalTeam: "DAL" },
      { year: 2031, round: 1, originalTeam: "DAL" },
      { year: 2031, round: 2, originalTeam: "DAL" },
    ],
  },
  {
    teamId: 8,
    teamAbbreviation: "DEN",
    picks: [
      { year: 2025, round: 1, originalTeam: "DEN" },
      { year: 2025, round: 2, originalTeam: "DEN" },
      { year: 2026, round: 1, originalTeam: "DEN" },
      { year: 2026, round: 2, originalTeam: "DEN" },
      { year: 2028, round: 1, originalTeam: "DEN" },
      { year: 2028, round: 2, originalTeam: "DEN" },
      { year: 2029, round: 1, originalTeam: "DEN" },
      { year: 2029, round: 2, originalTeam: "DEN" },
      { year: 2030, round: 1, originalTeam: "DEN" },
      { year: 2030, round: 2, originalTeam: "DEN" },
      { year: 2031, round: 1, originalTeam: "DEN" },
      { year: 2031, round: 2, originalTeam: "DEN" },
    ],
  },
  {
    teamId: 9,
    teamAbbreviation: "DET",
    picks: [
      { year: 2025, round: 1, originalTeam: "DET" },
      { year: 2025, round: 2, originalTeam: "DET" },
      { year: 2026, round: 1, originalTeam: "DET" },
      { year: 2026, round: 2, originalTeam: "DET" },
      { year: 2027, round: 1, originalTeam: "DET" },
      { year: 2027, round: 2, originalTeam: "DET" },
      { year: 2028, round: 1, originalTeam: "DET" },
      { year: 2028, round: 2, originalTeam: "DET" },
      { year: 2029, round: 1, originalTeam: "DET" },
      { year: 2029, round: 2, originalTeam: "DET" },
      { year: 2030, round: 1, originalTeam: "DET" },
      { year: 2030, round: 2, originalTeam: "DET" },
      { year: 2031, round: 1, originalTeam: "DET" },
      { year: 2031, round: 2, originalTeam: "DET" },
    ],
  },
  {
    teamId: 10,
    teamAbbreviation: "GSW",
    picks: [
      { year: 2025, round: 1, originalTeam: "GSW" },
      { year: 2025, round: 2, originalTeam: "GSW" },
      { year: 2026, round: 1, originalTeam: "GSW" },
      { year: 2026, round: 2, originalTeam: "GSW" },
      { year: 2027, round: 1, originalTeam: "GSW" },
      { year: 2027, round: 2, originalTeam: "GSW" },
      { year: 2028, round: 1, originalTeam: "GSW" },
      { year: 2028, round: 2, originalTeam: "GSW" },
      { year: 2029, round: 1, originalTeam: "GSW" },
      { year: 2029, round: 2, originalTeam: "GSW" },
      { year: 2030, round: 1, originalTeam: "GSW" },
      { year: 2030, round: 2, originalTeam: "GSW" },
      { year: 2031, round: 1, originalTeam: "GSW" },
      { year: 2031, round: 2, originalTeam: "GSW" },
    ],
  },
  {
    teamId: 11,
    teamAbbreviation: "HOU",
    picks: [
      { year: 2025, round: 1, originalTeam: "HOU" },
      { year: 2025, round: 1, originalTeam: "BKN", viaTradeWith: "BKN" },
      { year: 2025, round: 2, originalTeam: "HOU" },
      { year: 2026, round: 1, originalTeam: "HOU" },
      { year: 2026, round: 2, originalTeam: "HOU" },
      { year: 2027, round: 1, originalTeam: "HOU" },
      { year: 2027, round: 2, originalTeam: "HOU" },
      { year: 2028, round: 1, originalTeam: "HOU" },
      { year: 2028, round: 2, originalTeam: "HOU" },
      { year: 2029, round: 1, originalTeam: "HOU" },
      { year: 2029, round: 2, originalTeam: "HOU" },
      { year: 2030, round: 1, originalTeam: "HOU" },
      { year: 2030, round: 2, originalTeam: "HOU" },
      { year: 2031, round: 1, originalTeam: "HOU" },
      { year: 2031, round: 2, originalTeam: "HOU" },
    ],
  },
  {
    teamId: 12,
    teamAbbreviation: "IND",
    picks: [
      { year: 2025, round: 1, originalTeam: "IND" },
      { year: 2025, round: 2, originalTeam: "IND" },
      { year: 2026, round: 1, originalTeam: "IND" },
      { year: 2026, round: 2, originalTeam: "IND" },
      { year: 2027, round: 1, originalTeam: "IND" },
      { year: 2027, round: 2, originalTeam: "IND" },
      { year: 2028, round: 1, originalTeam: "IND" },
      { year: 2028, round: 2, originalTeam: "IND" },
      { year: 2029, round: 1, originalTeam: "IND" },
      { year: 2029, round: 2, originalTeam: "IND" },
      { year: 2030, round: 1, originalTeam: "IND" },
      { year: 2030, round: 2, originalTeam: "IND" },
      { year: 2031, round: 1, originalTeam: "IND" },
      { year: 2031, round: 2, originalTeam: "IND" },
    ],
  },
  {
    teamId: 13,
    teamAbbreviation: "LAC",
    picks: [
      { year: 2025, round: 2, originalTeam: "LAC" },
      { year: 2027, round: 1, originalTeam: "LAC" },
      { year: 2027, round: 2, originalTeam: "LAC" },
      { year: 2028, round: 1, originalTeam: "LAC" },
      { year: 2028, round: 2, originalTeam: "LAC" },
      { year: 2029, round: 1, originalTeam: "LAC" },
      { year: 2029, round: 2, originalTeam: "LAC" },
      { year: 2030, round: 1, originalTeam: "LAC" },
      { year: 2030, round: 2, originalTeam: "LAC" },
      { year: 2031, round: 1, originalTeam: "LAC" },
      { year: 2031, round: 2, originalTeam: "LAC" },
    ],
  },
  {
    teamId: 14,
    teamAbbreviation: "LAL",
    picks: [
      { year: 2025, round: 1, originalTeam: "LAL" },
      { year: 2025, round: 2, originalTeam: "LAL" },
      { year: 2026, round: 1, originalTeam: "LAL" },
      { year: 2026, round: 2, originalTeam: "LAL" },
      { year: 2027, round: 1, originalTeam: "LAL" },
      { year: 2027, round: 2, originalTeam: "LAL" },
      { year: 2028, round: 1, originalTeam: "LAL" },
      { year: 2028, round: 2, originalTeam: "LAL" },
      { year: 2029, round: 1, originalTeam: "LAL" },
      { year: 2029, round: 2, originalTeam: "LAL" },
      { year: 2030, round: 1, originalTeam: "LAL" },
      { year: 2030, round: 2, originalTeam: "LAL" },
      { year: 2031, round: 1, originalTeam: "LAL" },
      { year: 2031, round: 2, originalTeam: "LAL" },
    ],
  },
  {
    teamId: 15,
    teamAbbreviation: "MEM",
    picks: [
      { year: 2025, round: 1, originalTeam: "MEM" },
      { year: 2025, round: 2, originalTeam: "MEM" },
      { year: 2026, round: 1, originalTeam: "MEM" },
      { year: 2026, round: 2, originalTeam: "MEM" },
      { year: 2027, round: 1, originalTeam: "MEM" },
      { year: 2027, round: 2, originalTeam: "MEM" },
      { year: 2028, round: 1, originalTeam: "MEM" },
      { year: 2028, round: 2, originalTeam: "MEM" },
      { year: 2029, round: 1, originalTeam: "MEM" },
      { year: 2029, round: 2, originalTeam: "MEM" },
      { year: 2030, round: 1, originalTeam: "MEM" },
      { year: 2030, round: 2, originalTeam: "MEM" },
      { year: 2031, round: 1, originalTeam: "MEM" },
      { year: 2031, round: 2, originalTeam: "MEM" },
    ],
  },
  {
    teamId: 16,
    teamAbbreviation: "MIA",
    picks: [
      { year: 2025, round: 1, originalTeam: "MIA" },
      { year: 2025, round: 2, originalTeam: "MIA" },
      { year: 2026, round: 1, originalTeam: "MIA" },
      { year: 2026, round: 2, originalTeam: "MIA" },
      { year: 2027, round: 1, originalTeam: "MIA" },
      { year: 2027, round: 2, originalTeam: "MIA" },
      { year: 2028, round: 1, originalTeam: "MIA" },
      { year: 2028, round: 2, originalTeam: "MIA" },
      { year: 2029, round: 1, originalTeam: "MIA" },
      { year: 2029, round: 2, originalTeam: "MIA" },
      { year: 2030, round: 1, originalTeam: "MIA" },
      { year: 2030, round: 2, originalTeam: "MIA" },
      { year: 2031, round: 1, originalTeam: "MIA" },
      { year: 2031, round: 2, originalTeam: "MIA" },
    ],
  },
  {
    teamId: 17,
    teamAbbreviation: "MIL",
    picks: [
      { year: 2025, round: 1, originalTeam: "MIL" },
      { year: 2025, round: 2, originalTeam: "MIL" },
      { year: 2026, round: 1, originalTeam: "MIL" },
      { year: 2026, round: 2, originalTeam: "MIL" },
      { year: 2027, round: 1, originalTeam: "MIL" },
      { year: 2027, round: 2, originalTeam: "MIL" },
      { year: 2028, round: 1, originalTeam: "MIL" },
      { year: 2028, round: 2, originalTeam: "MIL" },
      { year: 2029, round: 1, originalTeam: "MIL" },
      { year: 2029, round: 2, originalTeam: "MIL" },
      { year: 2030, round: 1, originalTeam: "MIL" },
      { year: 2030, round: 2, originalTeam: "MIL" },
      { year: 2031, round: 1, originalTeam: "MIL" },
      { year: 2031, round: 2, originalTeam: "MIL" },
    ],
  },
  {
    teamId: 18,
    teamAbbreviation: "MIN",
    picks: [
      { year: 2025, round: 1, originalTeam: "MIN" },
      { year: 2025, round: 2, originalTeam: "MIN" },
      { year: 2026, round: 1, originalTeam: "MIN" },
      { year: 2026, round: 2, originalTeam: "MIN" },
      { year: 2027, round: 1, originalTeam: "MIN" },
      { year: 2027, round: 2, originalTeam: "MIN" },
      { year: 2028, round: 1, originalTeam: "MIN" },
      { year: 2028, round: 2, originalTeam: "MIN" },
      { year: 2029, round: 1, originalTeam: "MIN" },
      { year: 2029, round: 2, originalTeam: "MIN" },
      { year: 2030, round: 1, originalTeam: "MIN" },
      { year: 2030, round: 2, originalTeam: "MIN" },
      { year: 2031, round: 1, originalTeam: "MIN" },
      { year: 2031, round: 2, originalTeam: "MIN" },
    ],
  },
  {
    teamId: 19,
    teamAbbreviation: "NOP",
    picks: [
      { year: 2025, round: 1, originalTeam: "NOP" },
      { year: 2025, round: 2, originalTeam: "NOP" },
      { year: 2026, round: 1, originalTeam: "NOP" },
      { year: 2026, round: 2, originalTeam: "NOP" },
      { year: 2027, round: 1, originalTeam: "NOP" },
      { year: 2027, round: 2, originalTeam: "NOP" },
      { year: 2028, round: 1, originalTeam: "NOP" },
      { year: 2028, round: 2, originalTeam: "NOP" },
      { year: 2029, round: 1, originalTeam: "NOP" },
      { year: 2029, round: 2, originalTeam: "NOP" },
      { year: 2030, round: 1, originalTeam: "NOP" },
      { year: 2030, round: 2, originalTeam: "NOP" },
      { year: 2031, round: 1, originalTeam: "NOP" },
      { year: 2031, round: 2, originalTeam: "NOP" },
    ],
  },
  {
    teamId: 20,
    teamAbbreviation: "NYK",
    picks: [
      { year: 2025, round: 1, originalTeam: "NYK" },
      { year: 2025, round: 2, originalTeam: "NYK" },
      { year: 2026, round: 1, originalTeam: "NYK" },
      { year: 2026, round: 2, originalTeam: "NYK" },
      { year: 2027, round: 1, originalTeam: "NYK" },
      { year: 2027, round: 2, originalTeam: "NYK" },
      { year: 2028, round: 1, originalTeam: "NYK" },
      { year: 2028, round: 2, originalTeam: "NYK" },
      { year: 2029, round: 1, originalTeam: "NYK" },
      { year: 2029, round: 2, originalTeam: "NYK" },
      { year: 2030, round: 1, originalTeam: "NYK" },
      { year: 2030, round: 2, originalTeam: "NYK" },
      { year: 2031, round: 1, originalTeam: "NYK" },
      { year: 2031, round: 2, originalTeam: "NYK" },
    ],
  },
  {
    teamId: 21,
    teamAbbreviation: "OKC",
    picks: [
      { year: 2025, round: 1, originalTeam: "OKC" },
      { year: 2025, round: 1, originalTeam: "HOU", conditions: "Top 4 protected", viaTradeWith: "HOU" },
      { year: 2025, round: 1, originalTeam: "LAC", viaTradeWith: "LAC" },
      { year: 2025, round: 2, originalTeam: "OKC" },
      { year: 2025, round: 2, originalTeam: "PHI", viaTradeWith: "PHI" },
      { year: 2026, round: 1, originalTeam: "OKC" },
      { year: 2026, round: 1, originalTeam: "HOU", conditions: "Top 10 protected", viaTradeWith: "HOU" },
      { year: 2026, round: 1, originalTeam: "LAC", swapRights: true },
      { year: 2026, round: 2, originalTeam: "OKC" },
      { year: 2027, round: 1, originalTeam: "OKC" },
      { year: 2027, round: 1, originalTeam: "DEN", conditions: "Top 5 protected", viaTradeWith: "DEN" },
      { year: 2027, round: 2, originalTeam: "OKC" },
      { year: 2028, round: 1, originalTeam: "OKC" },
      { year: 2028, round: 2, originalTeam: "OKC" },
      { year: 2029, round: 1, originalTeam: "OKC" },
      { year: 2029, round: 1, originalTeam: "PHX", conditions: "Unprotected", viaTradeWith: "PHX" },
      { year: 2029, round: 2, originalTeam: "OKC" },
      { year: 2030, round: 1, originalTeam: "OKC" },
      { year: 2030, round: 2, originalTeam: "OKC" },
      { year: 2031, round: 1, originalTeam: "OKC" },
      { year: 2031, round: 2, originalTeam: "OKC" },
    ],
  },
  {
    teamId: 22,
    teamAbbreviation: "ORL",
    picks: [
      { year: 2025, round: 1, originalTeam: "ORL" },
      { year: 2025, round: 2, originalTeam: "ORL" },
      { year: 2026, round: 1, originalTeam: "ORL" },
      { year: 2026, round: 2, originalTeam: "ORL" },
      { year: 2027, round: 1, originalTeam: "ORL" },
      { year: 2027, round: 2, originalTeam: "ORL" },
      { year: 2028, round: 1, originalTeam: "ORL" },
      { year: 2028, round: 2, originalTeam: "ORL" },
      { year: 2029, round: 1, originalTeam: "ORL" },
      { year: 2029, round: 2, originalTeam: "ORL" },
      { year: 2030, round: 1, originalTeam: "ORL" },
      { year: 2030, round: 2, originalTeam: "ORL" },
      { year: 2031, round: 1, originalTeam: "ORL" },
      { year: 2031, round: 2, originalTeam: "ORL" },
    ],
  },
  {
    teamId: 23,
    teamAbbreviation: "PHI",
    picks: [
      { year: 2025, round: 1, originalTeam: "PHI" },
      { year: 2026, round: 1, originalTeam: "PHI" },
      { year: 2026, round: 2, originalTeam: "PHI" },
      { year: 2027, round: 1, originalTeam: "PHI" },
      { year: 2027, round: 2, originalTeam: "PHI" },
      { year: 2028, round: 1, originalTeam: "PHI" },
      { year: 2028, round: 2, originalTeam: "PHI" },
      { year: 2029, round: 1, originalTeam: "PHI" },
      { year: 2029, round: 2, originalTeam: "PHI" },
      { year: 2030, round: 1, originalTeam: "PHI" },
      { year: 2030, round: 2, originalTeam: "PHI" },
      { year: 2031, round: 1, originalTeam: "PHI" },
      { year: 2031, round: 2, originalTeam: "PHI" },
    ],
  },
  {
    teamId: 24,
    teamAbbreviation: "PHX",
    picks: [
      { year: 2025, round: 2, originalTeam: "PHX" },
      { year: 2026, round: 1, originalTeam: "PHX" },
      { year: 2026, round: 2, originalTeam: "PHX" },
      { year: 2028, round: 1, originalTeam: "PHX" },
      { year: 2028, round: 2, originalTeam: "PHX" },
      { year: 2030, round: 1, originalTeam: "PHX" },
      { year: 2030, round: 2, originalTeam: "PHX" },
      { year: 2031, round: 1, originalTeam: "PHX" },
      { year: 2031, round: 2, originalTeam: "PHX" },
    ],
  },
  {
    teamId: 25,
    teamAbbreviation: "POR",
    picks: [
      { year: 2025, round: 1, originalTeam: "POR" },
      { year: 2025, round: 2, originalTeam: "POR" },
      { year: 2026, round: 1, originalTeam: "POR" },
      { year: 2026, round: 2, originalTeam: "POR" },
      { year: 2027, round: 1, originalTeam: "POR" },
      { year: 2027, round: 2, originalTeam: "POR" },
      { year: 2028, round: 1, originalTeam: "POR" },
      { year: 2028, round: 2, originalTeam: "POR" },
      { year: 2029, round: 1, originalTeam: "POR" },
      { year: 2029, round: 2, originalTeam: "POR" },
      { year: 2030, round: 1, originalTeam: "POR" },
      { year: 2030, round: 2, originalTeam: "POR" },
      { year: 2031, round: 1, originalTeam: "POR" },
      { year: 2031, round: 2, originalTeam: "POR" },
    ],
  },
  {
    teamId: 26,
    teamAbbreviation: "SAC",
    picks: [
      { year: 2025, round: 1, originalTeam: "SAC" },
      { year: 2025, round: 2, originalTeam: "SAC" },
      { year: 2026, round: 1, originalTeam: "SAC" },
      { year: 2026, round: 2, originalTeam: "SAC" },
      { year: 2027, round: 1, originalTeam: "SAC" },
      { year: 2027, round: 2, originalTeam: "SAC" },
      { year: 2028, round: 1, originalTeam: "SAC" },
      { year: 2028, round: 2, originalTeam: "SAC" },
      { year: 2029, round: 1, originalTeam: "SAC" },
      { year: 2029, round: 2, originalTeam: "SAC" },
      { year: 2030, round: 1, originalTeam: "SAC" },
      { year: 2030, round: 2, originalTeam: "SAC" },
      { year: 2031, round: 1, originalTeam: "SAC" },
      { year: 2031, round: 2, originalTeam: "SAC" },
    ],
  },
  {
    teamId: 27,
    teamAbbreviation: "SAS",
    picks: [
      { year: 2025, round: 1, originalTeam: "SAS" },
      { year: 2025, round: 1, originalTeam: "ATL", conditions: "Top 1 protected", viaTradeWith: "ATL" },
      { year: 2025, round: 2, originalTeam: "SAS" },
      { year: 2026, round: 1, originalTeam: "SAS" },
      { year: 2026, round: 2, originalTeam: "SAS" },
      { year: 2027, round: 1, originalTeam: "SAS" },
      { year: 2027, round: 2, originalTeam: "SAS" },
      { year: 2028, round: 1, originalTeam: "SAS" },
      { year: 2028, round: 2, originalTeam: "SAS" },
      { year: 2029, round: 1, originalTeam: "SAS" },
      { year: 2029, round: 2, originalTeam: "SAS" },
      { year: 2030, round: 1, originalTeam: "SAS" },
      { year: 2030, round: 2, originalTeam: "SAS" },
      { year: 2031, round: 1, originalTeam: "SAS" },
      { year: 2031, round: 2, originalTeam: "SAS" },
    ],
  },
  {
    teamId: 28,
    teamAbbreviation: "TOR",
    picks: [
      { year: 2025, round: 1, originalTeam: "TOR" },
      { year: 2025, round: 2, originalTeam: "TOR" },
      { year: 2026, round: 1, originalTeam: "TOR" },
      { year: 2026, round: 2, originalTeam: "TOR" },
      { year: 2027, round: 1, originalTeam: "TOR" },
      { year: 2027, round: 2, originalTeam: "TOR" },
      { year: 2028, round: 1, originalTeam: "TOR" },
      { year: 2028, round: 2, originalTeam: "TOR" },
      { year: 2029, round: 1, originalTeam: "TOR" },
      { year: 2029, round: 2, originalTeam: "TOR" },
      { year: 2030, round: 1, originalTeam: "TOR" },
      { year: 2030, round: 2, originalTeam: "TOR" },
      { year: 2031, round: 1, originalTeam: "TOR" },
      { year: 2031, round: 2, originalTeam: "TOR" },
    ],
  },
  {
    teamId: 29,
    teamAbbreviation: "UTA",
    picks: [
      { year: 2025, round: 1, originalTeam: "UTA" },
      { year: 2025, round: 1, originalTeam: "CLE", conditions: "Top 10 protected", viaTradeWith: "CLE" },
      { year: 2025, round: 1, originalTeam: "MIN", viaTradeWith: "MIN" },
      { year: 2025, round: 2, originalTeam: "UTA" },
      { year: 2026, round: 1, originalTeam: "UTA" },
      { year: 2026, round: 1, originalTeam: "MIN", swapRights: true },
      { year: 2026, round: 2, originalTeam: "UTA" },
      { year: 2027, round: 1, originalTeam: "UTA" },
      { year: 2027, round: 1, originalTeam: "MIN", viaTradeWith: "MIN" },
      { year: 2027, round: 2, originalTeam: "UTA" },
      { year: 2028, round: 1, originalTeam: "UTA" },
      { year: 2028, round: 1, originalTeam: "MIN", swapRights: true },
      { year: 2028, round: 2, originalTeam: "UTA" },
      { year: 2029, round: 1, originalTeam: "UTA" },
      { year: 2029, round: 1, originalTeam: "MIN", conditions: "Unprotected", viaTradeWith: "MIN" },
      { year: 2029, round: 2, originalTeam: "UTA" },
      { year: 2030, round: 1, originalTeam: "UTA" },
      { year: 2030, round: 2, originalTeam: "UTA" },
      { year: 2031, round: 1, originalTeam: "UTA" },
      { year: 2031, round: 2, originalTeam: "UTA" },
    ],
  },
  {
    teamId: 30,
    teamAbbreviation: "WAS",
    picks: [
      { year: 2025, round: 1, originalTeam: "WAS" },
      { year: 2025, round: 2, originalTeam: "WAS" },
      { year: 2026, round: 1, originalTeam: "WAS" },
      { year: 2026, round: 2, originalTeam: "WAS" },
      { year: 2027, round: 1, originalTeam: "WAS" },
      { year: 2027, round: 2, originalTeam: "WAS" },
      { year: 2028, round: 1, originalTeam: "WAS" },
      { year: 2028, round: 2, originalTeam: "WAS" },
      { year: 2029, round: 1, originalTeam: "WAS" },
      { year: 2029, round: 2, originalTeam: "WAS" },
      { year: 2030, round: 1, originalTeam: "WAS" },
      { year: 2030, round: 2, originalTeam: "WAS" },
      { year: 2031, round: 1, originalTeam: "WAS" },
      { year: 2031, round: 2, originalTeam: "WAS" },
    ],
  },
];

/**
 * Seed the database with NBA draft picks data
 * Run with: npx convex run seedDraftPicks:seed
 *
 * Update the NBA_DRAFT_PICKS constant above when trades happen or after the draft,
 * then re-run this seed.
 */
export const seed = mutation({
  args: {},
  handler: async (ctx) => {
    let count = 0;

    for (const team of NBA_DRAFT_PICKS) {
      // Check if already exists
      const existing = await ctx.db
        .query("nbaDraftPicks")
        .withIndex("by_team", (q) => q.eq("teamId", team.teamId))
        .first();

      if (existing) {
        await ctx.db.patch(existing._id, {
          teamAbbreviation: team.teamAbbreviation,
          picks: team.picks,
          lastUpdated: Date.now(),
        });
      } else {
        await ctx.db.insert("nbaDraftPicks", {
          teamId: team.teamId,
          teamAbbreviation: team.teamAbbreviation,
          picks: team.picks,
          lastUpdated: Date.now(),
        });
      }
      count++;
    }

    return { seeded: count, teams: NBA_DRAFT_PICKS.length };
  },
});
